#THIS SCRIPT LOADS RELEVENT PACKAGES

#MY PERSONAL PACKAGE FOR HYDROLOGIC ANALYSIS
library(bansr)

#FOR IMPORTING DATA QUICKLY 
library(data.table)

#FOR DATA MANIPULATION AND GENERAL VISUALIZATION 
library(tidyverse)
library(janitor)

#FOR WORKING WITH DATES
library(lubridate)

#FOR CREATING GRAPH LAYOUTS 
library(patchwork)

#ADDITIONAL GRAPH THEMES
library(ggthemes)



