#THIS SCRIPT LOADS RELEVENT PACKAGES

#FOR DATA MANIPULATION AND GRAPHING 
library(tidyverse)
library(janitor)
library(fedmatch)

#FOR WORKING WITH DATES
library(lubridate)

#MY PERSONAL PACKAGE FOR HYDROLOGIC ANALYSIS
library(bansr)
