#ECOROOF ANALYSIS MASTER SCRIPT

#LOAD RELEVENT LIBRARIES
source("02_Scripts/Libraries.R")

#IMPORT RAIN DATA, PROCESS, AND PARSE STORMS
source("02_Scripts/Precipitation.R")

#IMPORT DISCHARGE DATA, AND PROCESS 
source("02_Scripts/Discharge.R")

#IMPORT POLLUTANT SAMPLE RESULTS AND PROCESS 
source("02_Scripts/Chemistry.R")

#CALCULATE UNIT AREA LOADING OF POLLUTANTS 
source("02_Scripts/Load.R")

#TEST THE UNIT AREA LOADS FOR NORMALITY ASSUMPTIONS 
source("02_Scripts/Statistics/Normality_testing.R")

#PERFORM FRIEDMAN TEST 
source("02_Scripts/Statistics/Friedman_tests.R")

#CALCULATE DISTRIBUTIONS OF EACH POLLUTANT AND COMPILE STATISTICS 
source("02_Scripts/Statistics/Distributions.R")

#CALCULATE TOTAL RUNOFF VOLUME AND RUNOFF RETENTION RATE FOR SAMPLING PERIOD 
source("02_Scripts/Retention.R")

#CREATE AND EXPORT GRAPHS 
source("02_Scripts/Graphs.R")

#COMPILE MARKDOWN REPORT 
source("02_Scripts/Report.R")

#EXPORT MARKDOWN REPORT 
source("02_Scripts/Exporting_Report.R")
